---
title: "Mar 18 Notes"
author: "Amber"
date: "2024-03-18"
output: html_document
---

## Model Checking: four conditions for inference

"L"inearity of relationship between variables
"I"ndependence of residuals
"N"ormality of residuals
"E"quality of variance (homoscedasticity) of residuals

  - L, N, and E can be evaluated by residual analysis (I depends on how data were collected)
  -Normality of residuals:
      - residuals should follow a normal distribution and be centered at zero
      - look at histogram of residuals...
  - Equality of residual variance:
      - Residuals shoudl show constant variance across the range of the explanatory variable
      - look at the plot of residuals relative to explanatory variable

Some checks
  - We can plot a histogram of residuals
  - We can plot residuals in relation to x variable
  - Use plot() function with a model as an argument
    - residuals vs fitted values of y (predicted y)- no structure
    - Q-Q plot of theoretical quantiles vs standardized quantiles for the residual values (these should fall along a line if residuals are normally distributed)
    - "Scale-location" plot = square root of the standarized residuals vs dited values of y; shows whether the magnitude of residuals differs across the fitted values of y
    - "Residuals vs Leverage" plot highlight whether there are any particular observations the disporportionate influence on the module
    - Shapiro-Wilk normality test
    
## Coding Challenge
```
{r}
f <- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/KamilarAndCooperData.csv"
d <- read_csv(f, col_names = TRUE)
```

Plot lifespan (MaxLongevity_m) vs female body mass (Body_mass_female_mean). Is the relationship linear? How might you transform?
```
{r}
p<- plot (x=d$MaxLongevity_m, y=d$Body_mass_female_mean)

#relationship is not linear

# ALTERNATIVELY
{r}
p <- ggplot(d, aes(x=Body_mass_female_mean, y=MaxLongevity_m)) + geom_point()
```

Run linear models of:

- lifespan ~ female body mass, lifespan ~log(female body mass), and log(lifespan) ~ log(female body mass)

```
lm1 <- lm(MaxLongevity_m ~Body_mass_female_mean, data=d)
plot(x=lm1$model$Body_mass_female_mean, y=lm1$residuals)

lm2 <- lm(MaxLongevity_m ~ log(Body_mass_female_mean), data=d)

lm3 <- lm(log(MaxLongevity_m) ~ log(Body_mass_female_mean), data=d)
```
- Generate the residuals for all three linear models, plot them in realtion to the corresponding explanatory variable, and make histograms of the residuals. Are they normally distributed?
```
{r}
par(mfrow = c(1, 3))
hist(lm1$residuals)
hist(lm2$residuals)
hist(lm3$residuals)
```

- Generate QQ plots for all three models. Do they appear normally distributed?
```
{r}
plot(x= lm1$model$Body_mass_female_mean, y=lm1$residuals)
plot(x= lm2$model$`log(Body_mass_female_mean)`, y=lm2$residuals)
plot(x= lm3$model$`log(Body_mass_female_mean)`, y=lm3$residuals)
```

- Run the plot() command for all three models. What do the plots suggest?
```
{r}
plot(lm1)
```

- Run Shapiro-Wilks tests on residuals for all three models. What do results suggest?
```
{r}
shapiro.test(lm1$model$Body_mass_female_mean)
shapiro.test(lm2$model$`log(Body_mass_female_mean)`)
shapiro.test(lm3$model$`log(Body_mass_female_mean)`)
```

## Categorical predictors
- We can use a discrete or categorical explanatory variable, made up of two or more factors [HE SWITCHED TOO FAST LOL]

## Coding Challenge
```
{r}
g <- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/AVONETdataset1.csv"
s <- read_csv(g, col_names = TRUE)

s <- s %>%
select(Species1, Family1, Order1, Beak.Width, Beak.Depth, Tarsus.Length, Wing.Length, Tail.Length, Mass, Habitat, Migration, Trophic.Level, Trophic.Niche, Min.Latitude, Max.Latitude, Centroid.Latitude,Range.Size)

ggplot(data = s |> drop_na(Trophic.Level),
aes(x=Trophic.Level, y= log(Mass))) +
geom_boxplot() + geom_jitter()

ggplot(data = s |> drop_na(Migration),
aes(x= as.factor(Migration), y= log(Mass))) +
geom_boxplot()
```

Run linear models and look at results (no need to drop_na)

```
{r}
m1 <- lm(log(Mass) ~Trophic.Level, data=s)
m2 <- lm(log(Mass) ~as.factor(Migration), data=s)
summary(m1)
summary(m2)

# The coefficient for the intercept, i.e., B0, reflects the estimate of the mean log(MAss) for the first of our level variables.
# The estimate for B1 is the estimated difference in mean log(MAss) associatedw ith being that level relative to the first reference level
```

You can relevel
```
{r}
s <- s |> mutate (Migration= relevel(Migration, ref= "3"))
m2 <- lm(log(Mass)) ~ Migration, data=s)
summary(m2)
```